pipeline {
  agent any
  environment {
    DOCKERHUB_CREDENTIALS = credentials('padma-dockerhub')
  }
  stages {
    stage('Build') {
      steps {
        sh 'sudo docker build -t padma/pa-alpine:latest .'
      }
    }
    stage('Login') {
      steps {
        sh 'sudo echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
      }
    }
    stage('Push') {
      steps {
        sh 'sudo docker push padma/pa-alpine:latest'
      }
    }
  }
  post {
    always {
      sh 'sudo docker logout'
    }
  }
}
